### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by voldemortensen** [jakubkulhan/chrome-devtools-protocol#16]
The culprit is here:
https://github.com/jakubkulhan/chrome-devtools-protocol/blob/d296e85a21686a6fcf2a934303eb3767b766affa/src/ChromeDevtoolsProtocol/DevtoolsClient.php#L109-L111

[Wrench\Client::receive()](https://github.com/varspool/Wrench/blob/2c297b5d655efaed22acbd0486d219f11b698b3c/lib/Client.php#L197) will return `null` if the websocket is no longer connected (I'm using a context with a timeout), throwing the foreach warning. I'm not sure what the best solution is here. Happy to write a patch though.

**Comment by jakubkulhan** [comment]
Hi, could you test behavior of using `$this->getWsClient()->receive() ?? []`? Does `DeadlineException` get thrown? If you, I'd be happy to accept such patch.

**Comment by mb0000** [comment]
Without wanting to be a "me too" post, I'm experiencing this problem as well.
Platform is Windows 7, Chrome 71.0.3578.98 (actually now I've just checked that it's wanting to update - sigh)

I notice that src/ChromeDevToolsProtocol/Instance/Launcher.php has `"--headless"` as the default argument(s). I have commented this out just to experiment with this Invalid argument problem and can happily make my simple test harrness work (with the Tab approach rather than the Session on for headless). When swapping back to headless using either Tab or Session domains, this problem occurs. However, I do notice that with headless + Session domain, that the last message sent out is a `Target.sendMessageToTarget` / `Page.enable` - it gets back a valid response (e.g. `{"id":4,"result":{}}`), but this (to be confirmed) is ignored and the program sits waiting for data, a timeout occurs and that's what results in an empty string coming back into DevtoolsClient.php line 109.

Hope that helps - I'm still patching and debugging, if I have more information, I'll update / post here.

**Comment by voldemortensen** [comment]
@jakubkulhan I've been testing today. When your suggestion didn't work I started digging more.

```php
$payloads = $this->getWsClient()->receive() ?? [];
var_dump($payloads);
foreach ($payloads as $payload) {
```

Results in this whenever there's a warning.
```php
string(0) ""
PHP Warning:  Invalid argument supplied for foreach() in /.../.../.../vendor/jakubkulhan/chrome-devtools-protocol/src/ChromeDevtoolsProtocol/DevtoolsClient.php on line 111
```

Digging more to see where this is coming from.

**Comment by voldemortensen** [comment]
And yes, `DeadlineException` does get thrown.

**Comment by mb0000** [comment]
> Without wanting to be a "me too" post, I'm experiencing this problem as well.
> Platform is Windows 7, Chrome 71.0.3578.98 (actually now I've just checked that it's wanting to update - sigh)
> 
> I notice that src/ChromeDevToolsProtocol/Instance/Launcher.php has `"--headless"` as the default argument(s). I have commented this out just to experiment with this Invalid argument problem and can happily make my simple test harrness work (with the Tab approach rather than the Session on for headless). When swapping back to headless using either Tab or Session domains, this problem occurs. However, I do notice that with headless + Session domain, that the last message sent out is a `Target.sendMessageToTarget` / `Page.enable` - it gets back a valid response (e.g. `{"id":4,"result":{}}`), but this (to be confirmed) is ignored and the program sits waiting for data, a timeout occurs and that's what results in an empty string coming back into DevtoolsClient.php line 109.
> 
> Hope that helps - I'm still patching and debugging, if I have more information, I'll update / post here.

Further to my earlier post, here's an update:
- I have created a test harness that allows headful / headless selection and Tab / Session selection
- When running headful + Tab and headless + Tab *using* a previously prepared --user-data-file parameter, the library works fine
- When running headless + Tab ( and also headless + Context) not using a previously prepared --user-data-file (so allowing the library to specify one), I experience this "Invalid argument supplied for each" issue. On investigation of that situation, it is because for me, headless Chrome is NOT actually creating a tab despite returning a valid tab json object at $instance->open()
- When running headless + Context using previously prepared --user-data-file, everything works until I call $devtools->close() at which point I get the "Invalid argument supplied for each" issue and then a long cascade of other resultant problems.
- I'll upload my test harness and output (with paths sanitised through paranoia) - I have xdebug installed so var_dumps include source line information but do also truncate long dump output.
[20190201-1244-headless-context_sanitised.txt](https://github.com/jakubkulhan/chrome-devtools-protocol/files/2821635/20190201-1244-headless-context_sanitised.txt)
[cdp_test_sanitised.php.txt](https://github.com/jakubkulhan/chrome-devtools-protocol/files/2821641/cdp_test_sanitised.php.txt)



- I have patched the libraries to provide diagnostic output, remove the default chrome --headless parameter, and capture the stdout + stderr of $instance - all without disturbing the line numbers from the unpatched libraries.

I suggest there are two areas for "attention"
- address the issue of the chrome profile not allowing tab creating when headless
- address the issue of the $devtools->close() when $devtools is a Session

Hope this helps
