### ISSUE TITLE
Wait until network requests finished loading

### ISSUE THREAD

**Issue by karlomikus** [jakubkulhan/chrome-devtools-protocol#21]
I'm generating pdf from html webpage with custom fonts from google fonts.

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Test</title>
    <link href="https://fonts.googleapis.com/css?family=Bahianita&display=swap" rel="stylesheet">
    <style>
        h1 {
            color: blue;
            font-family: 'Bahianita', cursive;
        }
    </style>
</head>
<body>
    <h1>Hello world</h1>
</body>
</html>
```

But the resulting pdf doesn't show custom fonts, since they are not loaded from the network.

Is it possible to implement something like `waitUntil` from [puppeteer](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-framegotourl-options), or is there any other way to wait until all network requests are finished loading.

**Comment by karlomikus** [comment]
Update:

I see that you can enable lifecycle events with
```php
$devtools->page()->setLifecycleEventsEnabled($ctx, SetLifecycleEventsEnabledRequest::builder()->setEnabled(true)->build());
```
And wait for `networkIdle` event like this:
```php
do {
    $lifecycleEvent = $devtools->page()->awaitLifecycleEvent($ctx)->name;
} while($lifecycleEvent !== 'networkIdle');
```

But that seems really dumb way to do it 😪

**Comment by jakubkulhan** [comment]
Hi. As you've found out, you may use lifecycle events emitted by Dev Tools Protocol. Another option would be to enable network events (`$devtools->network()->enable()`) and count network requests, or always wait until requests for fonts finish.

Also I've come across similar issue. The problem was that Google Fonts serve different file types based on a user agent string. TTF files are served to headless Chrome instead of WOFF2 (which are much smaller, therefore load faster). I've resolved this by setting `--user-agent=...` CLI flag to non-headless user agent string. However, I think this won't help if you set `font-display: swap` - you may need to use `font-display: block`.

This library offers only low-level API for Chrome Dev Tools Protocol. Currently I have no intention of adding higher-level APIs such as Puppeteer's wait until. Sorry.

**Comment by karlomikus** [comment]
Thanks for the info
