### ISSUE TITLE
How do you connect to a remote CDP browser server?

### ISSUE THREAD

**Issue by mikestopcontinues** [jakubkulhan/chrome-devtools-protocol#45]
I'm looking for a method like Puppeteer's [`.connect()` method](https://pptr.dev/api/puppeteer.puppeteernode.connect), that allows you to connect to a remote browser instance, but I can't seem to find it in the codebase. Can you provide just a small sample? I'd love to add your library to the [BrowserCat docs](https://www.browsercat.com/docs/connect-with/cdp-clients) to help a PHP user out. Thanks!

**Comment by jakubkulhan** [comment]
Hi, great service you offer! I've added a README section about [how to use with an already running browser](https://github.com/jakubkulhan/chrome-devtools-protocol?tab=readme-ov-file#using-an-already-running-chrome-browser). Is this something you had in mind?

**Comment by mikestopcontinues** [comment]
Thanks! I am to please. :)

Now that I'm looking at `Instance`, I see there's not an easy way to provide a full URL (`wss://api.browsercat.com/connect?apiKey=<KEY>`) or headers. Best I can see is by extending `GuzzleHttp\Client.request()` and ignoring the url parameter.

Would you be open to a PR to support a full url? And perhaps headers? If so, how would you like the change—updated constructor or a `RemoteInstance` class?

**Comment by jakubkulhan** [comment]
Oh, I see. `Instance` expects host and port because it gets CDP websocket URL using `/json/list`, `/json/version` HTTP requests. Once you want to connect directly to a single websocket URL, you can use [`DevtoolsClient` directly](https://github.com/jakubkulhan/chrome-devtools-protocol/blob/master/src/ChromeDevtoolsProtocol/DevtoolsClient.php#L37). So probably this is the way to connect to your service?

**Comment by mikestopcontinues** [comment]
That's perfect. It's possible to pass all params to BrowserCat via query string, so that covers all the bases. I'll get a docs page up this week. Thanks for your help!
